### ISSUE TITLE
BelenongsTo breaks if QuickCreate form has BooleanGroup field

### ISSUE THREAD

**Issue by Otienoh** [64robots/nova-fields#150]
When you try to fetch the search or use the dropdown you get the error below, when you remove the Booleangroup field everything works fine
```
[2019-12-30 22:32:38] local.ERROR: Method Illuminate\Support\Collection::isAssoc does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Support\\Collection::isAssoc does not exist. at C:\\Code\\www\\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\Macroable.php:103)
[stacktrace]
#0 C:\\Code\\www\\vendor\\laravel\
ova\\src\\Fields\\BooleanGroup.php(38): Illuminate\\Support\\Collection->__call('isAssoc', Array)
#1 [internal function]: Laravel\\Nova\\Fields\\BooleanGroup->Laravel\\Nova\\Fields\\{closure}('admin', 'admin')
#2 C:\\Code\\www\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Collection.php(638): array_map(Object(Closure), Array, Array)
#3 C:\\Code\\www\\vendor\\laravel\
ova\\src\\Fields\\BooleanGroup.php(41): Illuminate\\Support\\Collection->map(Object(Closure))
#4 C:\\Code\\www\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php(547): Laravel\\Nova\\Fields\\BooleanGroup->Laravel\\Nova\\Fields\\{closure}(Object(Illuminate\\Support\\Collection))
```

**Comment by disitec** [comment]
Sorry for the delay. Can you provide the exact code example that causes the error for you? Thanks

**Comment by Otienoh** [comment]
Closing this as I am using default Nova field
