### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_c') in nova-fields

### ISSUE THREAD

**Issue by ghost** [64robots/nova-fields#232]
PHP : 7.3
Laravel : 8
Nova : 4
Getting this error while use `DateTime` Field

```
TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (nova-fields:1:258215)
    at qn (runtime-core.esm-bundler.js:914:44)
    at Ee.fn (runtime-core.esm-bundler.js:5649:57)
    at Ee.run (reactivity.esm-bundler.js:190:25)
    at B.e.update (runtime-core.esm-bundler.js:5763:56)
    at B (runtime-core.esm-bundler.js:5777:9)
    at M (runtime-core.esm-bundler.js:5559:9)
    at L (runtime-core.esm-bundler.js:5517:17)
    at h (runtime-core.esm-bundler.js:5119:21)
    at A (runtime-core.esm-bundler.js:5303:13)
```

![image](https://github.com/64robots/nova-fields/assets/111680744/3c4347c7-fc3a-4ffd-ba42-cb383de9ef50)

**Comment by garrettmassey1** [comment]
Have you tested any other fields from this package? I've noticed the same error on the Row field.

**Comment by annerland** [comment]
+1
