### ISSUE TITLE
Getting ERROR: Declaration of R64\NovaFields\Configurable::readOnly()

### ISSUE THREAD

**Issue by Otienoh** [64robots/nova-fields#79]
### Problem
Hello,
 It seems the recent Nova version (2.0.1) release introduces some breaking changes to the package. After a `composer update` I started receive this error when openning any form where I use the package `Declaration of R64\NovaFields\Configurable::readOnly() should be compatible with Laravel\Nova\Fields\Field::readonly($callback)`. 

### Steps to reproduce
- update you composer dependencies
- Ensure you have the latest Nova version
- Visit any resource where you are using the fields from this package

### Current Quick fix
Removed all the useage of R64 nova fields in my application by replacing `use R64\NovaFields\BelongsTo` with `use Laravel\Nova\Fields\BelongsTo` and everything started working well.

### Full Stacktrace
For additional context see below
```
[2019-03-28 15:50:02] production.ERROR: Declaration of R64\NovaFields\Configurable::readOnly() should be compatible with Laravel\Nova\Fields\Field::readonly($callback) {"userId":1,"exception":"[object] (ErrorException(code: 0): Declaration of R64\\NovaFields\\Configurable::readOnly() should be compatible with Laravel\\Nova\\Fields\\Field::readonly($callback) at /home/forge/staging.m-shule.com/vendor/64robots/nova-fields/src/Number.php:7)
[stacktrace]
#0 /home/forge/staging.m-shule.com/vendor/sentry/sentry/src/ErrorHandler.php(194): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Declaration of ...', '/home/forge/sta...', 7)
#1 /home/forge/staging.m-shule.com/vendor/64robots/nova-fields/src/Number.php(7): Sentry\\ErrorHandler->handleError(2, 'Declaration of ...', '/home/forge/sta...', 7, Array)
#2 /home/forge/staging.m-shule.com/vendor/composer/ClassLoader.php(444): include('/home/forge/sta...')
#3 /home/forge/staging.m-shule.com/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/home/forge/sta...')
#4 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('R64\\\\NovaFields\\\\...')
#5 /home/forge/staging.m-shule.com/app/Nova/School.php(113): spl_autoload_call('R64\\\\NovaFields\\\\...')
#6 /home/forge/staging.m-shule.com/vendor/laravel/nova/src/ResolvesFields.php(281): App\\Nova\\School->fields(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#7 /home/forge/staging.m-shule.com/vendor/laravel/nova/src/ResolvesFields.php(173): Laravel\\Nova\\Resource->availableFields(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#8 /home/forge/staging.m-shule.com/vendor/laravel/nova/src/ResolvesFields.php(86): Laravel\\Nova\\Resource->resolveFields(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), Object(Closure))
#9 /home/forge/staging.m-shule.com/vendor/laravel/nova/src/Http/Controllers/CreationFieldController.php(23): Laravel\\Nova\\Resource->creationFields(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#10 [internal function]: Laravel\\Nova\\Http\\Controllers\\CreationFieldController->index(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), 'schools')
#11 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#12 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#13 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\CreationFieldController), 'index')
#14 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#15 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#16 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/forge/staging.m-shule.com/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/forge/staging.m-shule.com/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/forge/staging.m-shule.com/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/forge/staging.m-shule.com/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/forge/staging.m-shule.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Clo... 
```
### Screenshot
![unknown](https://user-images.githubusercontent.com/8632640/55197560-0886c280-51c4-11e9-8d66-e09d184edc1c.png)

**Comment by disitec** [comment]
Fixed in 0.7.0 🌮
